name: saglamspot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter  # Flutter SDK'sı, Flutter uygulamalarını geliştirmek için temel gerekliliktir.

  # iOS stil ikonlar için Cupertino Icons paketi (opsiyonel).
  #cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.3  # Uygulama durumu yönetimi için BLoC (Business Logic Component) desenini sağlar.

  equatable: ^2.0.5  # Nesnelerin eşitliğini karşılaştırmak için kullanılır, BLoC ve diğer state yönetimi durumlarında faydalıdır.

  # Functional Programming
  dartz: ^0.10.1  # Fonksiyonel programlama için gerekli yapıları sağlar (Option, Either gibi).

  # Network
  dio: ^5.3.2  # HTTP isteklerini yapmak için kullanılan güçlü bir ağ kütüphanesi.

  # Local Storage
  shared_preferences: ^2.2.0  # Kalıcı yerel veri depolama için kullanılır (key-value çifti).

  # Service Locator
  internet_connection_checker: ^3.0.1  # İnternet bağlantısının durumunu kontrol etmek için kullanılır.

  # Firebase
  firebase_core: ^3.6.0  # Firebase servislerini kullanmak için gerekli temel yapı.
  cloud_firestore: ^5.4.4  # Firebase'in NoSQL veritabanı olan Cloud Firestore'u kullanmak için.
  firebase_storage: ^12.3.2  # Firebase'in dosya depolama hizmetini kullanmak için.

  # URL ve Dosya Seçimi
  url_launcher: ^6.0.20  # Uygulama içinden URL açmak için.
  image_picker: ^0.8.7+5  # Mobil cihazlarda kamera ve galeriye erişim için.
  file_picker: ^8.1.7  # Web ortamında dosya seçimi yapmayı sağlar.

  # Uluslararasılaştırma
  intl: ^0.18.1  # Tarih, saat ve sayı biçimlendirme gibi işlemler için.

  # Diğer Kütüphaneler
  flutter_riverpod: ^2.4.10  # State yönetimi için Riverpod.
  freezed_annotation: ^2.4.1  # Immutable data class oluşturmak için.
  riverpod_annotation: ^2.3.4  # Riverpod için anotasyon desteği.
  fpdart: ^1.1.1  # Fonksiyonel programlama desteği.

  # Kod Üretimi
  build_runner: ^2.4.8  # Kod üretimi için kullanılan araç.
  freezed: ^2.4.7  # Freezed ile veri sınıfları oluşturmak için.
  riverpod_generator: ^2.3.9  # Riverpod için kod üretimi.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0  # Dart kodunun kalitesini artırmak için lint kuralları sağlar.
  build_runner: ^2.4.8  # Kod üretimi için kullanılan araç.
  injectable_generator: ^2.4.1  # Injectable için otomatik kod üretimi.


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bicycle_france.jpg
    - assets/images/volvo_transport.jpg
    - assets/images/tram_bus.jpg
    - assets/images/map.jpg
    - assets/images/book_room.jpg
    - assets/images/man_walk.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
