// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyRa49tC9AgYas2KawEu3uJW9uwUn8m90',
    appId: '1:46238966317:web:aefbcba4de66c4d425cea4',
    messagingSenderId: '46238966317',
    projectId: 'gen-lang-client-0004103607',
    authDomain: 'gen-lang-client-0004103607.firebaseapp.com',
    storageBucket: 'gen-lang-client-0004103607.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADsj3JVxAE8ctwR_NpQHuMSAKKSKqQzUs',
    appId: '1:46238966317:android:0c5beb56dd776fa525cea4',
    messagingSenderId: '46238966317',
    projectId: 'gen-lang-client-0004103607',
    storageBucket: 'gen-lang-client-0004103607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9c3VHm7c3nU5KOnQ6gqJKpkQvuyoXGs',
    appId: '1:46238966317:ios:eb4e747f8637cce925cea4',
    messagingSenderId: '46238966317',
    projectId: 'gen-lang-client-0004103607',
    storageBucket: 'gen-lang-client-0004103607.firebasestorage.app',
    iosBundleId: 'com.ferdidrgn.saglamspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq9c3VHm7c3nU5KOnQ6gqJKpkQvuyoXGs',
    appId: '1:46238966317:ios:eb4e747f8637cce925cea4',
    messagingSenderId: '46238966317',
    projectId: 'gen-lang-client-0004103607',
    storageBucket: 'gen-lang-client-0004103607.firebasestorage.app',
    iosBundleId: 'com.ferdidrgn.saglamspot',
  );
}
