// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZG-PkPWxp2PMahl1nEN0GwUmIqlLf2I',
    appId: '1:257014284345:web:2092e3dd24aae5f022cde8',
    messagingSenderId: '257014284345',
    projectId: 'saglamspotflutter-2a1a8',
    authDomain: 'saglamspotflutter-2a1a8.firebaseapp.com',
    storageBucket: 'saglamspotflutter-2a1a8.firebasestorage.app',
    measurementId: 'G-3Z4LKNJ3N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRvkZvzIwVhux0meoOhzh_XXlIc4pkVw',
    appId: '1:257014284345:android:f4fdeb7628cacdc722cde8',
    messagingSenderId: '257014284345',
    projectId: 'saglamspotflutter-2a1a8',
    storageBucket: 'saglamspotflutter-2a1a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAlEat9lQ7TLBlygy4t9G8KSxslotgMCw',
    appId: '1:257014284345:ios:f4ebd9281ca0379622cde8',
    messagingSenderId: '257014284345',
    projectId: 'saglamspotflutter-2a1a8',
    storageBucket: 'saglamspotflutter-2a1a8.firebasestorage.app',
    iosBundleId: 'com.ferdidrgn.saglamspot',
  );
}
